// Códigos de error generales
export enum GeneralErrorCode {
  INVALID_INPUT = 'INVALID_INPUT',
  UNAUTHORIZED = 'UNAUTHORIZED',
  FORBIDDEN = 'FORBIDDEN',
  NOT_FOUND = 'NOT_FOUND',
  CONFLICT = 'CONFLICT',
  INTERNAL_SERVER_ERROR = 'INTERNAL_SERVER_ERROR',
  BAD_REQUEST = 'BAD_REQUEST',
  SERVICE_UNAVAILABLE = 'SERVICE_UNAVAILABLE',
  METHOD_NOT_ALLOWED = 'METHOD_NOT_ALLOWED',
  VALIDATION_ERROR = 'VALIDATION_ERROR',
  TOO_MANY_REQUESTS = 'TOO_MANY_REQUESTS',
  PAYLOAD_TOO_LARGE = 'PAYLOAD_TOO_LARGE',
  DATABASE_CONNECTION_ERROR = 'DATABASE_CONNECTION_ERROR',
}

export enum PaymentErrorCode {
  PAYMENT_PROVIDER_ERROR = 'PAYMENT_PROVIDER_ERROR',
  PAYMENT_PROVIDER_NO_RESPONSE = 'PAYMENT_PROVIDER_NO_RESPONSE',
  CARD_NOT_SUPPORTED = 'CARD_NOT_SUPPORTED',
  INVALID_CARD_DATA = 'INVALID_CARD_DATA',
  INSUFFICIENT_FUNDS = 'INSUFFICIENT_FUNDS',
  TRANSACTION_DECLINED = 'TRANSACTION_DECLINED',
}

export enum UserErrorCode {
  // Auth & Identity
  USER_NOT_FOUND = 'USER_NOT_FOUND',
  USER_ALREADY_EXISTS = 'USER_ALREADY_EXISTS',
  INVALID_CREDENTIALS = 'INVALID_CREDENTIALS',
  EMAIL_ALREADY_IN_USE = 'EMAIL_ALREADY_IN_USE',
  PHONE_ALREADY_IN_USE = 'PHONE_ALREADY_IN_USE',

  // Status
  USER_IS_INACTIVE = 'USER_IS_INACTIVE',
  USER_SUSPENDED = 'USER_SUSPENDED',
  USER_DELETED = 'USER_DELETED',
  ACCOUNT_LOCKED = 'ACCOUNT_LOCKED',

  // Verification
  TOKEN_EXPIRED = 'TOKEN_EXPIRED',
  INVALID_TOKEN = 'INVALID_TOKEN',
  VERIFICATION_CODE_INVALID = 'VERIFICATION_CODE_INVALID',
  MAX_ATTEMPTS_EXCEEDED = 'MAX_ATTEMPTS_EXCEEDED',

  // Profile & Data
  PROFILE_UPDATE_FAILED = 'PROFILE_UPDATE_FAILED',
  PASSWORD_CHANGE_FAILED = 'PASSWORD_CHANGE_FAILED',
  ADDRESS_NOT_FOUND = 'ADDRESS_NOT_FOUND',
  INVALID_USER_ROLE = 'INVALID_USER_ROLE',
}

export enum AuthErrorCode {
  // Método de login / rol
  LOGIN_METHOD_NOT_ALLOWED = 'LOGIN_METHOD_NOT_ALLOWED',
  EMAIL_VERIFICATION_REQUIRED = 'EMAIL_VERIFICATION_REQUIRED',
  ACCOUNT_ALREADY_VERIFIED = 'ACCOUNT_ALREADY_VERIFIED',
  ROLE_NOT_CONFIGURED = 'ROLE_NOT_CONFIGURED',
  TOO_MANY_IP_ATTEMPTS = 'TOO_MANY_IP_ATTEMPTS',
  // Estado del complejo en login
  COMPLEX_INACTIVE = 'COMPLEX_INACTIVE',
  COMPLEX_SUSPENDED = 'COMPLEX_SUSPENDED',
  COMPLEX_OWNER_NOT_FOUND = 'COMPLEX_OWNER_NOT_FOUND',
  // QR login
  QR_TOKEN_INVALID = 'QR_TOKEN_INVALID',
  QR_TOKEN_ALREADY_USED = 'QR_TOKEN_ALREADY_USED',
  QR_TOKEN_EXPIRED = 'QR_TOKEN_EXPIRED',
  QR_PIN_REQUIRED = 'QR_PIN_REQUIRED',
  QR_PIN_NOT_CONFIGURED = 'QR_PIN_NOT_CONFIGURED',
  QR_PIN_INVALID = 'QR_PIN_INVALID',
  QR_PIN_GENERATION_FAILED = 'QR_PIN_GENERATION_FAILED',
  // Tokens / sesión
  INVALID_TOKEN_TYPE = 'INVALID_TOKEN_TYPE',
  TOKEN_REVOKED = 'TOKEN_REVOKED',
  TOKEN_REUSE_DETECTED = 'TOKEN_REUSE_DETECTED',
  SESSION_FINGERPRINT_MISMATCH = 'SESSION_FINGERPRINT_MISMATCH',
  SESSION_EXPIRED = 'SESSION_EXPIRED',
  SESSION_TERMINATED = 'SESSION_TERMINATED',
  REFRESH_TOKEN_MALFORMED = 'REFRESH_TOKEN_MALFORMED',
  // OTP
  OTP_NOT_FOUND = 'OTP_NOT_FOUND',
  OTP_EXPIRED = 'OTP_EXPIRED',
  OTP_MAX_ATTEMPTS = 'OTP_MAX_ATTEMPTS',
  OTP_INVALID = 'OTP_INVALID',
  OTP_RATE_LIMIT = 'OTP_RATE_LIMIT',
  // Dispositivo + PIN (residentes)
  DEVICE_ID_REQUIRED = 'DEVICE_ID_REQUIRED',
  DEVICE_NOT_LINKED = 'DEVICE_NOT_LINKED',
  DEVICE_REVOKED = 'DEVICE_REVOKED',
  DEVICE_NOT_FOUND = 'DEVICE_NOT_FOUND',
  // Freno del alta de equipos nuevos con documento + clave. NO es el bloqueo de
  // la cuenta: los dispositivos ya vinculados siguen entrando con normalidad.
  DEVICE_ENROLLMENT_THROTTLED = 'DEVICE_ENROLLMENT_THROTTLED',
  // Clave de acceso del residente: una por cuenta, sirve en los equipos ya
  // vinculados. El bloqueo es de la cuenta, no del dispositivo.
  ACCESS_CODE_INVALID = 'ACCESS_CODE_INVALID',
  ACCESS_CODE_TOO_WEAK = 'ACCESS_CODE_TOO_WEAK',
  ACCESS_CODE_LOCKED = 'ACCESS_CODE_LOCKED',
  ACCESS_CODE_NOT_SET = 'ACCESS_CODE_NOT_SET',
  ACCESS_CODE_REQUIRED = 'ACCESS_CODE_REQUIRED',
  CURRENT_ACCESS_CODE_REQUIRED = 'CURRENT_ACCESS_CODE_REQUIRED',
  ACCESS_CODE_NOT_ALLOWED = 'ACCESS_CODE_NOT_ALLOWED',
  // Login por WhatsApp entrante (reverse-OTP)
  WA_LOGIN_NOT_CONFIGURED = 'WA_LOGIN_NOT_CONFIGURED',
  WA_LOGIN_CHALLENGE_NOT_FOUND = 'WA_LOGIN_CHALLENGE_NOT_FOUND',
  WA_LOGIN_CHALLENGE_EXPIRED = 'WA_LOGIN_CHALLENGE_EXPIRED',
  WA_LOGIN_CHALLENGE_PENDING = 'WA_LOGIN_CHALLENGE_PENDING',
  // El canje desde otro dispositivo devuelve CHALLENGE_NOT_FOUND a propósito:
  // distinguirlo revelaría que el challenge existe.
  WA_LOGIN_CHALLENGE_CONSUMED = 'WA_LOGIN_CHALLENGE_CONSUMED',
  WA_LOGIN_RATE_LIMIT = 'WA_LOGIN_RATE_LIMIT',
  // Aprobación de ingreso por push
  APPROVAL_NOT_FOUND = 'APPROVAL_NOT_FOUND',
  APPROVAL_EXPIRED = 'APPROVAL_EXPIRED',
  APPROVAL_PENDING = 'APPROVAL_PENDING',
  APPROVAL_DENIED = 'APPROVAL_DENIED',
  APPROVAL_CONSUMED = 'APPROVAL_CONSUMED',
  APPROVAL_ALREADY_RESOLVED = 'APPROVAL_ALREADY_RESOLVED',
  APPROVAL_RATE_LIMIT = 'APPROVAL_RATE_LIMIT',
}

export enum RolesErrorCode {
  ROL_NOT_FOUND = 'ROL_NOT_FOUND',
  ROL_ALREADY_EXISTS = 'ROL_ALREADY_EXISTS',
  ROL_IS_ACTIVE = 'ROL_IS_ACTIVE',
  ROL_IS_INACTIVE = 'ROL_IS_INACTIVE',
  ROL_ALREADY_DELETED = 'ROL_ALREADY_DELETED',
  PARENT_ROL_INACTIVE = 'PARENT_ROL_INACTIVE',
  ROL_HAS_ACTIVE_CHILDREN = 'ROL_HAS_ACTIVE_CHILDREN',
  ROL_HAS_ACTIVE_USERS = 'ROL_HAS_ACTIVE_USERS',
  ROL_HAS_USERS_ASSIGNED = 'ROL_HAS_USERS_ASSIGNED',
  SYSTEM_ROL_CANNOT_BE_MODIFIED = 'SYSTEM_ROL_CANNOT_BE_MODIFIED',
  INSUFFICIENT_PERMISSIONS = 'INSUFFICIENT_PERMISSIONS',
  PERMISSION_NOT_FOUND = 'PERMISSION_NOT_FOUND',
  PERMISSION_ALREADY_ASSIGNED = 'PERMISSION_ALREADY_ASSIGNED',
  CIRCULAR_DEPENDENCY_DETECTED = 'CIRCULAR_DEPENDENCY_DETECTED',
  ROL_HAS_INACTIVE_PERMISSIONS = 'ROL_HAS_INACTIVE_PERMISSIONS',
}

export enum PermissionErrorCode {
  // Errores de registro y creación de usuario
  PERMISSION_ALREADY_EXISTS = 'PERMISSION_ALREADY_EXISTS',
  PERMISSION_NOT_EXISTS = 'PERMISSION_NOT_EXISTS',
  PERMISSION_CREATION_FAILED = 'PERMISSION_CREATION_FAILED',
  PERMISSION_IS_NOT_ACTIVE = 'PERMISSION_IS_NOT_ACTIVE',
  PERMISSION_Is_NOT_DESACTIVE = 'PERMISSION_Is_NOT_DESACTIVE',
  MAX_RESEND_ATTEMPTS_REACHED = 'MAX_RESEND_ATTEMPTS_REACHED',
  CIRCULAR_DEPENDENCY_DETECTED = 'CIRCULAR_DEPENDENCY_DETECTED',
  SYSTEM_PERMISSION_MODIFICATION_NOT_ALLOWED = 'SYSTEM_PERMISSION_MODIFICATION_NOT_ALLOWED',

  // Errores de autenticación
  PERMISSION_NOT_FOUND = 'PERMISSION_NOT_FOUND',
  PERMISSION_UNAUTHORIZED = 'PERMISSION_UNAUTHORIZED',
  // Errores de actualización de perfil
  PERMISSION_UPDATE_FAILED = 'PERMISSION_UPDATE_FAILED',
  // Errores de permisos y PERMISSIONes
  PERMISSION_INSUFFICIENT_PERMISSIONS = 'PERMISSION_INSUFFICIENT_PERMISSIONS',
  PERMISSION_ASSIGNMENT_FAILED = 'PERMISSION_ASSIGNMENT_FAILED',
  PERMISSION_REMOVAL_FAILED = 'PERMISSION_REMOVAL_FAILED',
  PERMISSION_NOT_VALID = 'PERMISSION_NOT_VALID',

  // Errores de eliminación de cuenta o datos
  PERMISSION_DELETION_FAILED = 'PERMISSION_DELETION_FAILED',

  PERMISSION_ALREADY_DELETED = 'PERMISSION_ALREADY_DELETED',
  PERMISSION_ALREADY_ACTIVE = 'PERMISSION_ALREADY_ACTIVE',
  SYSTEM_PERMISSION_DELETION_NOT_ALLOWED = 'SYSTEM_PERMISSION_DELETION_NOT_ALLOWED',
  PERMISSION_HAS_ACTIVE_DEPENDENCIES = 'PERMISSION_HAS_ACTIVE_DEPENDENCIES',
  PERMISSION_HAS_ACTIVE_ASSIGNMENTS = 'PERMISSION_HAS_ACTIVE_ASSIGNMENTS',
}

export enum LogisticsErrorCode {
  // Vehículos
  VEHICLE_NOT_FOUND = 'VEHICLE_NOT_FOUND',
  VEHICLE_ALREADY_IN_COMPLEX = 'VEHICLE_ALREADY_IN_COMPLEX',
  VEHICLE_PLATE_DUPLICATE = 'VEHICLE_PLATE_DUPLICATE',
  VEHICLE_NOT_ACTIVE = 'VEHICLE_NOT_ACTIVE',
  VEHICLE_SUSPENDED = 'VEHICLE_SUSPENDED',
  VEHICLE_ALREADY_REMOVED = 'VEHICLE_ALREADY_REMOVED',
  MAX_VEHICLES_PER_UNIT = 'MAX_VEHICLES_PER_UNIT',
  PARKING_SPOT_NOT_AVAILABLE = 'PARKING_SPOT_NOT_AVAILABLE',
  INVALID_PLATE_FORMAT = 'INVALID_PLATE_FORMAT',
  // Paquetes
  PARCEL_NOT_FOUND = 'PARCEL_NOT_FOUND',
  PARCEL_ALREADY_DELIVERED = 'PARCEL_ALREADY_DELIVERED',
  PARCEL_STORAGE_FULL = 'PARCEL_STORAGE_FULL',
  // Rotación de parqueaderos
  ROTATION_CONFIG_NOT_FOUND = 'ROTATION_CONFIG_NOT_FOUND',
  ROTATION_INACTIVE = 'ROTATION_INACTIVE',
  ROTATION_NOT_NEEDED = 'ROTATION_NOT_NEEDED',
}

export enum AccessErrorCode {
  VISIT_NOT_AUTHORIZED = 'VISIT_NOT_AUTHORIZED',
  VISIT_EXPIRED = 'VISIT_EXPIRED',
  VISIT_NOT_FOUND = 'VISIT_NOT_FOUND',
  VISIT_ALREADY_INSIDE = 'VISIT_ALREADY_INSIDE',
  VISIT_ALREADY_COMPLETED = 'VISIT_ALREADY_COMPLETED',
  VISIT_ALREADY_DENIED = 'VISIT_ALREADY_DENIED',
  VISITOR_BLACK_LISTED = 'VISITOR_BLACK_LISTED',
  VISITOR_NOT_FOUND = 'VISITOR_NOT_FOUND',
  VISITOR_ALREADY_BLACKLISTED = 'VISITOR_ALREADY_BLACKLISTED',
  VISITOR_NOT_BLACKLISTED = 'VISITOR_NOT_BLACKLISTED',
  QR_CODE_INVALID = 'QR_CODE_INVALID',
  QR_CODE_ALREADY_USED = 'QR_CODE_ALREADY_USED',
  QR_CODE_EXPIRED = 'QR_CODE_EXPIRED',
  ENTRY_DENIED_BY_RESIDENT = 'ENTRY_DENIED_BY_RESIDENT',
  GUARD_NOT_ASSIGNED_TO_COMPLEX = 'GUARD_NOT_ASSIGNED_TO_COMPLEX',
  DEVICE_OFFLINE = 'DEVICE_OFFLINE',
}

export enum ResidentErrorCode {
  RESIDENT_NOT_FOUND = 'RESIDENT_NOT_FOUND',
  RESIDENT_ALREADY_ACTIVE = 'RESIDENT_ALREADY_ACTIVE',
  RESIDENT_ALREADY_PENDING = 'RESIDENT_ALREADY_PENDING',
  RESIDENT_ALREADY_MAIN = 'RESIDENT_ALREADY_MAIN',
  RESIDENT_SUSPENDED = 'RESIDENT_SUSPENDED',
  RESIDENT_MOVED_OUT = 'RESIDENT_MOVED_OUT',
  RESIDENT_REJECTED = 'RESIDENT_REJECTED',
  USER_ALREADY_RESIDENT_IN_COMPLEX = 'USER_ALREADY_RESIDENT_IN_COMPLEX',
  CANNOT_REMOVE_ACTIVE_RESIDENT = 'CANNOT_REMOVE_ACTIVE_RESIDENT',
}

export enum FinanceErrorCode {
  FEE_CONFIG_NOT_FOUND = 'FEE_CONFIG_NOT_FOUND',
  FEE_CONFIG_ALREADY_EXISTS = 'FEE_CONFIG_ALREADY_EXISTS',
  FEE_CONFIG_INACTIVE = 'FEE_CONFIG_INACTIVE',
  FEE_CHARGE_NOT_FOUND = 'FEE_CHARGE_NOT_FOUND',
  FEE_CHARGE_ALREADY_PAID = 'FEE_CHARGE_ALREADY_PAID',
  FEE_CHARGE_CANCELLED = 'FEE_CHARGE_CANCELLED',
  FEE_CHARGE_ALREADY_EXISTS = 'FEE_CHARGE_ALREADY_EXISTS',
  PAYMENT_NOT_FOUND = 'PAYMENT_NOT_FOUND',
  PAYMENT_EXCEEDS_BALANCE = 'PAYMENT_EXCEEDS_BALANCE',
  PAYMENT_ALREADY_REVERSED = 'PAYMENT_ALREADY_REVERSED',
  PERIOD_INVALID_FORMAT = 'PERIOD_INVALID_FORMAT',
  PERIOD_ALREADY_CLOSED = 'PERIOD_ALREADY_CLOSED',
  PERIOD_IN_FUTURE = 'PERIOD_IN_FUTURE',
  EXPENSE_NOT_FOUND = 'EXPENSE_NOT_FOUND',
  EXPENSE_ALREADY_REVERSED = 'EXPENSE_ALREADY_REVERSED',
  INCOME_NOT_FOUND = 'INCOME_NOT_FOUND',
  INCOME_ALREADY_REVERSED = 'INCOME_ALREADY_REVERSED',
  RECURRING_CHARGE_NOT_FOUND = 'RECURRING_CHARGE_NOT_FOUND',
  // Emisión de cargos
  CHARGE_EMISSION_NOT_FOUND = 'CHARGE_EMISSION_NOT_FOUND',
  CHARGE_EMISSION_ALREADY_EXISTS = 'CHARGE_EMISSION_ALREADY_EXISTS',
  CHARGE_EMISSION_NOT_DRAFT = 'CHARGE_EMISSION_NOT_DRAFT',
  CHARGE_EMISSION_RULE_OVERLAP = 'CHARGE_EMISSION_RULE_OVERLAP',
  CHARGE_EMISSION_NO_LINES = 'CHARGE_EMISSION_NO_LINES',
  // Ledger contable (partida doble)
  INVALID_AMOUNT = 'INVALID_AMOUNT',
  UNBALANCED_ENTRY = 'UNBALANCED_ENTRY',
  PUC_ACCOUNT_INVALID = 'PUC_ACCOUNT_INVALID',
  PUC_ACCOUNT_NOT_FOUND = 'PUC_ACCOUNT_NOT_FOUND',
  PUC_ACCOUNT_NOT_LEAF = 'PUC_ACCOUNT_NOT_LEAF',
  PUC_ACCOUNT_HAS_MOVEMENTS = 'PUC_ACCOUNT_HAS_MOVEMENTS',
  PUC_ACCOUNT_CODE_DUPLICATE = 'PUC_ACCOUNT_CODE_DUPLICATE',
  PUC_ACCOUNT_IN_USE = 'PUC_ACCOUNT_IN_USE',
  ACCOUNTING_DOC_NOT_FOUND = 'ACCOUNTING_DOC_NOT_FOUND',
  ACCOUNTING_DOC_IMMUTABLE = 'ACCOUNTING_DOC_IMMUTABLE',
  NO_PREPAID_BALANCE = 'NO_PREPAID_BALANCE',
}

export enum NoteErrorCode {
  NOTE_NOT_FOUND = 'NOTE_NOT_FOUND',
  NOTE_ACCESS_DENIED = 'NOTE_ACCESS_DENIED',
  NOTE_ALREADY_DELETED = 'NOTE_ALREADY_DELETED',
  NOTE_COMPLEX_MISMATCH = 'NOTE_COMPLEX_MISMATCH',
}

export enum MessageErrorCode {
  MESSAGE_NOT_FOUND = 'MESSAGE_NOT_FOUND',
  MESSAGE_ACCESS_DENIED = 'MESSAGE_ACCESS_DENIED',
}

export enum AccessRequestErrorCode {
  ALREADY_ASSIGNED = 'ALREADY_ASSIGNED',
  REQUEST_ALREADY_PENDING = 'REQUEST_ALREADY_PENDING',
  REQUEST_NOT_FOUND = 'REQUEST_NOT_FOUND',
  REQUEST_ALREADY_RESOLVED = 'REQUEST_ALREADY_RESOLVED',
}

export enum SupervisorErrorCode {
  COMPLEX_NOT_FOUND_FOR_CHECKIN = 'COMPLEX_NOT_FOUND_FOR_CHECKIN',
  SUPERVISOR_NOT_ASSIGNED_TO_COMPLEX = 'SUPERVISOR_NOT_ASSIGNED_TO_COMPLEX',
  SUPERVISOR_VISIT_ALREADY_ACTIVE = 'SUPERVISOR_VISIT_ALREADY_ACTIVE',
  SUPERVISOR_VISIT_NOT_FOUND = 'SUPERVISOR_VISIT_NOT_FOUND',
  SUPERVISOR_VISIT_REQUIRED_FOR_NOTE = 'SUPERVISOR_VISIT_REQUIRED_FOR_NOTE',
  SUPERVISOR_OUT_OF_RANGE = 'SUPERVISOR_OUT_OF_RANGE',
  GPS_COORDINATES_REQUIRED = 'GPS_COORDINATES_REQUIRED',
}

export enum ParkingErrorCode {
  PARKING_RECORD_NOT_FOUND = 'PARKING_RECORD_NOT_FOUND',
  PARKING_VEHICLE_NOT_INSIDE = 'PARKING_VEHICLE_NOT_INSIDE',
  PARKING_VEHICLE_ALREADY_EXITED = 'PARKING_VEHICLE_ALREADY_EXITED',
  PARKING_RATE_NOT_FOUND = 'PARKING_RATE_NOT_FOUND',
  PARKING_RATE_INACTIVE = 'PARKING_RATE_INACTIVE',
  VISITOR_PARKING_CONFIG_NOT_FOUND = 'VISITOR_PARKING_CONFIG_NOT_FOUND',
}

export enum SpecialNumberErrorCode {
  SPECIAL_NUMBER_NOT_FOUND = 'SPECIAL_NUMBER_NOT_FOUND',
  SPECIAL_NUMBER_ACCESS_DENIED = 'SPECIAL_NUMBER_ACCESS_DENIED',
  SPECIAL_NUMBER_COMPLEX_MISMATCH = 'SPECIAL_NUMBER_COMPLEX_MISMATCH',
  SPECIAL_NUMBER_COMPLEX_REQUIRED = 'SPECIAL_NUMBER_COMPLEX_REQUIRED',
  MAX_NUMBERS_REACHED = 'MAX_NUMBERS_REACHED',
}

export enum ComplexErrorCode {
  COMPLEX_NOT_FOUND = 'COMPLEX_NOT_FOUND',
  COMPLEX_ALREADY_EXISTS = 'COMPLEX_ALREADY_EXISTS',
  COMPLEX_SUBSCRIPTION_EXPIRED = 'COMPLEX_SUBSCRIPTION_EXPIRED',
  BUILDING_NOT_FOUND = 'BUILDING_NOT_FOUND',
  BUILDING_ALREADY_EXISTS = 'BUILDING_ALREADY_EXISTS',
  BUILDING_HAS_ACTIVE_UNITS = 'BUILDING_HAS_ACTIVE_UNITS',
  UNIT_NOT_FOUND = 'UNIT_NOT_FOUND',
  UNIT_ALREADY_EXISTS = 'UNIT_ALREADY_EXISTS',
  UNIT_IS_OCCUPIED = 'UNIT_IS_OCCUPIED',
  INVALID_UNIT_FORMAT = 'INVALID_UNIT_FORMAT',
  MAX_RESIDENTS_REACHED = 'MAX_RESIDENTS_REACHED',
  PLAN_LIMIT_EXCEEDED = 'PLAN_LIMIT_EXCEEDED',
  GEOCODING_ADDRESS_NOT_FOUND = 'GEOCODING_ADDRESS_NOT_FOUND',
  GEOCODING_SERVICE_UNAVAILABLE = 'GEOCODING_SERVICE_UNAVAILABLE',
  /**
   * El complejo no tiene contratado —o tiene apagado— el módulo que atiende la
   * operación. El front lo usa para explicar en vez de mostrar un 403 pelado.
   */
  COMPLEX_MODULE_DISABLED = 'COMPLEX_MODULE_DISABLED',
}

export enum AmenityErrorCode {
  AMENITY_NOT_FOUND = 'AMENITY_NOT_FOUND',
  AMENITY_NAME_ALREADY_EXISTS = 'AMENITY_NAME_ALREADY_EXISTS',
  AMENITY_NOT_ACTIVE = 'AMENITY_NOT_ACTIVE',
  AMENITY_SCHEDULE_NOT_FOUND = 'AMENITY_SCHEDULE_NOT_FOUND',
  AMENITY_SCHEDULE_INVALID_RANGE = 'AMENITY_SCHEDULE_INVALID_RANGE',
  AMENITY_SCHEDULE_OVERLAP = 'AMENITY_SCHEDULE_OVERLAP',
  AMENITY_BLACKOUT_NOT_FOUND = 'AMENITY_BLACKOUT_NOT_FOUND',
  AMENITY_BLACKOUT_INVALID_RANGE = 'AMENITY_BLACKOUT_INVALID_RANGE',
  BOOKING_NOT_FOUND = 'BOOKING_NOT_FOUND',
  BOOKING_INVALID_RANGE = 'BOOKING_INVALID_RANGE',
  BOOKING_OUTSIDE_SCHEDULE = 'BOOKING_OUTSIDE_SCHEDULE',
  BOOKING_ON_BLACKOUT = 'BOOKING_ON_BLACKOUT',
  BOOKING_SLOT_UNAVAILABLE = 'BOOKING_SLOT_UNAVAILABLE',
  BOOKING_INVALID_SLOT_START = 'BOOKING_INVALID_SLOT_START',
  BOOKING_DURATION_TOO_SHORT = 'BOOKING_DURATION_TOO_SHORT',
  BOOKING_DURATION_TOO_LONG = 'BOOKING_DURATION_TOO_LONG',
  BOOKING_TOO_SOON = 'BOOKING_TOO_SOON',
  BOOKING_TOO_FAR_AHEAD = 'BOOKING_TOO_FAR_AHEAD',
  BOOKING_IN_THE_PAST = 'BOOKING_IN_THE_PAST',
  BOOKING_EXCEEDS_CAPACITY = 'BOOKING_EXCEEDS_CAPACITY',
  BOOKING_UNIT_LIMIT_REACHED = 'BOOKING_UNIT_LIMIT_REACHED',
  BOOKING_UNIT_MONTHLY_LIMIT = 'BOOKING_UNIT_MONTHLY_LIMIT',
  BOOKING_UNIT_HAS_DEBT = 'BOOKING_UNIT_HAS_DEBT',
  BOOKING_INVALID_STATUS = 'BOOKING_INVALID_STATUS',
  BOOKING_ALREADY_CHECKED_IN = 'BOOKING_ALREADY_CHECKED_IN',
  BOOKING_NOT_CHECKED_IN = 'BOOKING_NOT_CHECKED_IN',
  BOOKING_CHECK_IN_TOO_EARLY = 'BOOKING_CHECK_IN_TOO_EARLY',
  BOOKING_ACCESS_CODE_INVALID = 'BOOKING_ACCESS_CODE_INVALID',
  BOOKING_NOT_OWNED_BY_UNIT = 'BOOKING_NOT_OWNED_BY_UNIT',
  BOOKING_SPAN_NOT_AVAILABLE = 'BOOKING_SPAN_NOT_AVAILABLE',
  BOOKING_INVALID_DAY_RANGE = 'BOOKING_INVALID_DAY_RANGE',
  DAMAGE_ALREADY_CHARGED = 'DAMAGE_ALREADY_CHARGED',
  DAMAGE_NOT_CHARGEABLE_YET = 'DAMAGE_NOT_CHARGEABLE_YET',
  CLEANING_SERVICE_NOT_AVAILABLE = 'CLEANING_SERVICE_NOT_AVAILABLE',
  CLEANING_WINDOW_COLLIDES = 'CLEANING_WINDOW_COLLIDES',
  CLEANING_NOT_EDITABLE = 'CLEANING_NOT_EDITABLE',
  BOOKING_NOTHING_TO_COLLECT = 'BOOKING_NOTHING_TO_COLLECT',
  BOOKING_ALREADY_COLLECTED = 'BOOKING_ALREADY_COLLECTED',
  BOOKING_CHARGE_ALREADY_PAID = 'BOOKING_CHARGE_ALREADY_PAID',
  REFUND_NOTHING_TO_PAY = 'REFUND_NOTHING_TO_PAY',
  REFUND_ALREADY_PAID = 'REFUND_ALREADY_PAID',
}

export enum PetErrorCode {
  // Ficha de la mascota
  PET_NOT_FOUND = 'PET_NOT_FOUND',
  PET_PHOTO_REQUIRED = 'PET_PHOTO_REQUIRED',
  PET_MICROCHIP_DUPLICATE = 'PET_MICROCHIP_DUPLICATE',
  PET_MAX_PER_UNIT_REACHED = 'PET_MAX_PER_UNIT_REACHED',
  PET_INVALID_STATUS = 'PET_INVALID_STATUS',
  PET_ALREADY_APPROVED = 'PET_ALREADY_APPROVED',
  /** La ficha ya fue validada: el residente no la edita, la administración sí. */
  PET_LOCKED_AFTER_APPROVAL = 'PET_LOCKED_AFTER_APPROVAL',
  PET_COMPLEX_MISMATCH = 'PET_COMPLEX_MISMATCH',
  // Póliza obligatoria para razas de manejo especial (Ley 2054/2020)
  PET_INSURANCE_REQUIRED = 'PET_INSURANCE_REQUIRED',
  PET_INSURANCE_EXPIRED = 'PET_INSURANCE_EXPIRED',
  // Reportes de convivencia
  PET_INCIDENT_NOT_FOUND = 'PET_INCIDENT_NOT_FOUND',
  PET_INCIDENT_ACCESS_DENIED = 'PET_INCIDENT_ACCESS_DENIED',
  PET_INCIDENT_INVALID_STATUS = 'PET_INCIDENT_INVALID_STATUS',
  PET_INCIDENT_EVIDENCE_REQUIRED = 'PET_INCIDENT_EVIDENCE_REQUIRED',
  PET_INCIDENT_OCCURRED_IN_FUTURE = 'PET_INCIDENT_OCCURRED_IN_FUTURE',
  PET_INCIDENT_TARGET_REQUIRED = 'PET_INCIDENT_TARGET_REQUIRED',
  PET_INCIDENT_REPORTING_DISABLED = 'PET_INCIDENT_REPORTING_DISABLED',
  // Debido proceso: la sanción no puede adelantarse al plazo de descargos
  PET_INCIDENT_DEFENSE_WINDOW_OPEN = 'PET_INCIDENT_DEFENSE_WINDOW_OPEN',
  PET_INCIDENT_STATEMENT_WINDOW_CLOSED = 'PET_INCIDENT_STATEMENT_WINDOW_CLOSED',
  PET_INCIDENT_FINE_AMOUNT_REQUIRED = 'PET_INCIDENT_FINE_AMOUNT_REQUIRED',
  PETS_MODULE_DISABLED = 'PETS_MODULE_DISABLED',
}

export enum MaintenanceErrorCode {
  // Ticket
  MAINTENANCE_TICKET_NOT_FOUND = 'MAINTENANCE_TICKET_NOT_FOUND',
  MAINTENANCE_TICKET_ACCESS_DENIED = 'MAINTENANCE_TICKET_ACCESS_DENIED',
  MAINTENANCE_TICKET_INVALID_STATUS = 'MAINTENANCE_TICKET_INVALID_STATUS',
  /** El tablero no deja saltarse el trámite: cada salto tiene su mutation. */
  MAINTENANCE_TRANSITION_NOT_ALLOWED = 'MAINTENANCE_TRANSITION_NOT_ALLOWED',
  MAINTENANCE_EVIDENCE_REQUIRED = 'MAINTENANCE_EVIDENCE_REQUIRED',
  MAINTENANCE_RESOLUTION_EVIDENCE_REQUIRED = 'MAINTENANCE_RESOLUTION_EVIDENCE_REQUIRED',
  MAINTENANCE_OCCURRED_IN_FUTURE = 'MAINTENANCE_OCCURRED_IN_FUTURE',
  MAINTENANCE_REASON_REQUIRED = 'MAINTENANCE_REASON_REQUIRED',
  MAINTENANCE_MODULE_DISABLED = 'MAINTENANCE_MODULE_DISABLED',
  MAINTENANCE_REPORTING_DISABLED = 'MAINTENANCE_REPORTING_DISABLED',
  // Ubicación
  MAINTENANCE_LOCATION_REQUIRED = 'MAINTENANCE_LOCATION_REQUIRED',
  MAINTENANCE_LOCATION_MISMATCH = 'MAINTENANCE_LOCATION_MISMATCH',
  MAINTENANCE_LOCATION_OUT_OF_COMPLEX = 'MAINTENANCE_LOCATION_OUT_OF_COMPLEX',
  MAINTENANCE_TAG_NOT_FOUND = 'MAINTENANCE_TAG_NOT_FOUND',
  MAINTENANCE_TAG_DUPLICATE = 'MAINTENANCE_TAG_DUPLICATE',
  MAINTENANCE_TAG_INACTIVE = 'MAINTENANCE_TAG_INACTIVE',
  // Responsable
  MAINTENANCE_ASSIGNEE_REQUIRED = 'MAINTENANCE_ASSIGNEE_REQUIRED',
  MAINTENANCE_ASSIGNEE_CONFLICT = 'MAINTENANCE_ASSIGNEE_CONFLICT',
  MAINTENANCE_ASSIGNEE_NOT_IN_COMPLEX = 'MAINTENANCE_ASSIGNEE_NOT_IN_COMPLEX',
  MAINTENANCE_VENDOR_NOT_FOUND = 'MAINTENANCE_VENDOR_NOT_FOUND',
  MAINTENANCE_VENDOR_DUPLICATE = 'MAINTENANCE_VENDOR_DUPLICATE',
  MAINTENANCE_VENDOR_INACTIVE = 'MAINTENANCE_VENDOR_INACTIVE',
  MAINTENANCE_VENDOR_HAS_OPEN_TICKETS = 'MAINTENANCE_VENDOR_HAS_OPEN_TICKETS',
  // Plazos
  MAINTENANCE_SLA_INVALID = 'MAINTENANCE_SLA_INVALID',
  MAINTENANCE_SLA_NOT_FOUND = 'MAINTENANCE_SLA_NOT_FOUND',
  // Adhesiones, calificación y reapertura
  MAINTENANCE_ALREADY_ENDORSED = 'MAINTENANCE_ALREADY_ENDORSED',
  MAINTENANCE_ENDORSE_CLOSED = 'MAINTENANCE_ENDORSE_CLOSED',
  MAINTENANCE_RATING_NOT_ALLOWED = 'MAINTENANCE_RATING_NOT_ALLOWED',
  MAINTENANCE_ALREADY_RATED = 'MAINTENANCE_ALREADY_RATED',
  MAINTENANCE_REOPEN_WINDOW_CLOSED = 'MAINTENANCE_REOPEN_WINDOW_CLOSED',
  MAINTENANCE_REOPEN_LIMIT = 'MAINTENANCE_REOPEN_LIMIT',
  MAINTENANCE_DUPLICATE_SELF = 'MAINTENANCE_DUPLICATE_SELF',
}

export enum MarketplaceErrorCode {
  // Publicación
  LISTING_NOT_FOUND = 'LISTING_NOT_FOUND',
  LISTING_ACCESS_DENIED = 'LISTING_ACCESS_DENIED',
  LISTING_INVALID_STATUS = 'LISTING_INVALID_STATUS',
  /** El aviso ya se publicó: se pausa o se retira, no se edita a escondidas. */
  LISTING_LOCKED_AFTER_PUBLISH = 'LISTING_LOCKED_AFTER_PUBLISH',
  LISTING_IMAGES_REQUIRED = 'LISTING_IMAGES_REQUIRED',
  LISTING_TOO_MANY_IMAGES = 'LISTING_TOO_MANY_IMAGES',
  LISTING_MAX_PER_UNIT_REACHED = 'LISTING_MAX_PER_UNIT_REACHED',
  LISTING_PRICE_REQUIRED = 'LISTING_PRICE_REQUIRED',
  LISTING_EXPIRED = 'LISTING_EXPIRED',
  /** Publicar sin aceptar las condiciones deja a la copropiedad sin respaldo. */
  LISTING_TERMS_NOT_ACCEPTED = 'LISTING_TERMS_NOT_ACCEPTED',
  LISTING_WANTED_DISABLED = 'LISTING_WANTED_DISABLED',
  LISTING_OWNER_WITHOUT_UNIT = 'LISTING_OWNER_WITHOUT_UNIT',
  // Categorías
  MARKETPLACE_CATEGORY_NOT_FOUND = 'MARKETPLACE_CATEGORY_NOT_FOUND',
  MARKETPLACE_CATEGORY_INACTIVE = 'MARKETPLACE_CATEGORY_INACTIVE',
  MARKETPLACE_CATEGORY_DUPLICATE = 'MARKETPLACE_CATEGORY_DUPLICATE',
  /** No se borra una categoría con avisos vivos: quedarían huérfanos. */
  MARKETPLACE_CATEGORY_IN_USE = 'MARKETPLACE_CATEGORY_IN_USE',
  // Contacto e interés
  LISTING_CONTACT_SELF = 'LISTING_CONTACT_SELF',
  LISTING_CONTACT_NOT_AVAILABLE = 'LISTING_CONTACT_NOT_AVAILABLE',
  LISTING_PHONE_HIDDEN = 'LISTING_PHONE_HIDDEN',
  // Reportes
  LISTING_REPORT_NOT_FOUND = 'LISTING_REPORT_NOT_FOUND',
  LISTING_ALREADY_REPORTED = 'LISTING_ALREADY_REPORTED',
  LISTING_REPORT_SELF = 'LISTING_REPORT_SELF',
  LISTING_REPORT_ALREADY_RESOLVED = 'LISTING_REPORT_ALREADY_RESOLVED',
  // Ajustes del módulo
  MARKETPLACE_SETTINGS_INVALID = 'MARKETPLACE_SETTINGS_INVALID',
  MARKETPLACE_MODULE_DISABLED = 'MARKETPLACE_MODULE_DISABLED',
  MARKETPLACE_CATEGORY_KIND_MISMATCH = 'MARKETPLACE_CATEGORY_KIND_MISMATCH',
  // Chat entre vecinos
  CONVERSATION_NOT_FOUND = 'CONVERSATION_NOT_FOUND',
  /** Solo los dos participantes leen la conversación; la administración no. */
  CONVERSATION_ACCESS_DENIED = 'CONVERSATION_ACCESS_DENIED',
  /** El aviso se cerró, venció o se retiró: el chat queda de solo lectura. */
  CONVERSATION_READ_ONLY = 'CONVERSATION_READ_ONLY',
  /** Uno de los dos bloqueó al otro. No se dice cuál. */
  CONVERSATION_BLOCKED = 'CONVERSATION_BLOCKED',
  MESSAGE_EMPTY = 'MESSAGE_EMPTY',
  MESSAGE_RATE_LIMITED = 'MESSAGE_RATE_LIMITED',
  /** El conjunto apagó el contacto por teléfono en los clasificados. */
  PHONE_SHARING_DISABLED = 'PHONE_SHARING_DISABLED',
  PHONE_NOT_AVAILABLE = 'PHONE_NOT_AVAILABLE',
  /** La administración cerró la conversación por un reporte. */
  CONVERSATION_CLOSED_BY_MODERATION = 'CONVERSATION_CLOSED_BY_MODERATION',
  CONVERSATION_ALREADY_REPORTED = 'CONVERSATION_ALREADY_REPORTED',
  CONVERSATION_REPORT_NOT_FOUND = 'CONVERSATION_REPORT_NOT_FOUND',
  CONVERSATION_REPORT_ALREADY_RESOLVED = 'CONVERSATION_REPORT_ALREADY_RESOLVED',
  MESSAGE_IMAGE_REQUIRED = 'MESSAGE_IMAGE_REQUIRED',
  MESSAGE_NOT_IMAGE = 'MESSAGE_NOT_IMAGE',
}

/**
 * Acciones ejecutadas desde el aviso (`executeNotificationAction`).
 *
 * Los descriptores que viaja el expediente son para PINTAR; la autorización se
 * vuelve a evaluar aquí. Estos códigos son los que ve la web cuando el estado
 * cambió entre que se abrió el aviso y se pulsó el botón —otro administrador ya
 * resolvió el caso, o el plazo de descargos sigue corriendo.
 */
export enum NotificationActionErrorCode {
  /** El módulo dueño del asunto no expone acciones. */
  NOTIFICATION_ACTION_UNSUPPORTED = 'NOTIFICATION_ACTION_UNSUPPORTED',
  /** El código no está entre las acciones de HOY para quien la pide. */
  NOTIFICATION_ACTION_UNAVAILABLE = 'NOTIFICATION_ACTION_UNAVAILABLE',
  /** Existe, pero el trámite no la permite todavía. */
  NOTIFICATION_ACTION_BLOCKED = 'NOTIFICATION_ACTION_BLOCKED',
  NOTIFICATION_ACTION_FIELD_REQUIRED = 'NOTIFICATION_ACTION_FIELD_REQUIRED',
}
