
// Códigos de error generales
export enum GeneralErrorCode {
  INVALID_INPUT = 'INVALID_INPUT',
  UNAUTHORIZED = 'UNAUTHORIZED',
  FORBIDDEN = 'FORBIDDEN',
  NOT_FOUND = 'NOT_FOUND',
  CONFLICT = 'CONFLICT',
  INTERNAL_SERVER_ERROR = 'INTERNAL_SERVER_ERROR',
  BAD_REQUEST = 'BAD_REQUEST',
  SERVICE_UNAVAILABLE = 'SERVICE_UNAVAILABLE',
  METHOD_NOT_ALLOWED = 'METHOD_NOT_ALLOWED',
  VALIDATION_ERROR = 'VALIDATION_ERROR',
  TOO_MANY_REQUESTS = 'TOO_MANY_REQUESTS',
  DATABASE_CONNECTION_ERROR = 'DATABASE_CONNECTION_ERROR',
}

export enum PaymentErrorCode {
  PAYMENT_PROVIDER_ERROR = 'PAYMENT_PROVIDER_ERROR',
  PAYMENT_PROVIDER_NO_RESPONSE = 'PAYMENT_PROVIDER_NO_RESPONSE',
  CARD_NOT_SUPPORTED = 'CARD_NOT_SUPPORTED',
  INVALID_CARD_DATA = 'INVALID_CARD_DATA',
  INSUFFICIENT_FUNDS = 'INSUFFICIENT_FUNDS',
  TRANSACTION_DECLINED = 'TRANSACTION_DECLINED',
}

export enum UserErrorCode {
  // Auth & Identity
  USER_NOT_FOUND = 'USER_NOT_FOUND',
  USER_ALREADY_EXISTS = 'USER_ALREADY_EXISTS',
  INVALID_CREDENTIALS = 'INVALID_CREDENTIALS',
  EMAIL_ALREADY_IN_USE = 'EMAIL_ALREADY_IN_USE',
  PHONE_ALREADY_IN_USE = 'PHONE_ALREADY_IN_USE',
  
  // Status
  USER_IS_INACTIVE = 'USER_IS_INACTIVE',
  USER_SUSPENDED = 'USER_SUSPENDED',
  USER_DELETED = 'USER_DELETED',
  ACCOUNT_LOCKED = 'ACCOUNT_LOCKED',
  
  // Verification
  TOKEN_EXPIRED = 'TOKEN_EXPIRED',
  INVALID_TOKEN = 'INVALID_TOKEN',
  VERIFICATION_CODE_INVALID = 'VERIFICATION_CODE_INVALID',
  MAX_ATTEMPTS_EXCEEDED = 'MAX_ATTEMPTS_EXCEEDED',
  
  // Profile & Data
  PROFILE_UPDATE_FAILED = 'PROFILE_UPDATE_FAILED',
  PASSWORD_CHANGE_FAILED = 'PASSWORD_CHANGE_FAILED',
  ADDRESS_NOT_FOUND = 'ADDRESS_NOT_FOUND',
  INVALID_USER_ROLE = 'INVALID_USER_ROLE',
}

export enum RolesErrorCode {
  ROL_NOT_FOUND = 'ROL_NOT_FOUND',
  ROL_ALREADY_EXISTS = 'ROL_ALREADY_EXISTS',
  ROL_IS_ACTIVE = 'ROL_IS_ACTIVE',
  ROL_IS_INACTIVE = 'ROL_IS_INACTIVE',
  ROL_ALREADY_DELETED = 'ROL_ALREADY_DELETED',
  PARENT_ROL_INACTIVE = 'PARENT_ROL_INACTIVE',
  ROL_HAS_ACTIVE_CHILDREN = 'ROL_HAS_ACTIVE_CHILDREN',
  ROL_HAS_ACTIVE_USERS = 'ROL_HAS_ACTIVE_USERS',
  ROL_HAS_USERS_ASSIGNED = 'ROL_HAS_USERS_ASSIGNED',
  SYSTEM_ROL_CANNOT_BE_MODIFIED = 'SYSTEM_ROL_CANNOT_BE_MODIFIED',
  INSUFFICIENT_PERMISSIONS = 'INSUFFICIENT_PERMISSIONS',
  PERMISSION_NOT_FOUND = 'PERMISSION_NOT_FOUND',
  PERMISSION_ALREADY_ASSIGNED = 'PERMISSION_ALREADY_ASSIGNED',
  CIRCULAR_DEPENDENCY_DETECTED = 'CIRCULAR_DEPENDENCY_DETECTED',
  ROL_HAS_INACTIVE_PERMISSIONS = 'ROL_HAS_INACTIVE_PERMISSIONS',
}

export enum PermissionErrorCode {
  // Errores de registro y creación de usuario
  PERMISSION_ALREADY_EXISTS = 'PERMISSION_ALREADY_EXISTS',
  PERMISSION_NOT_EXISTS = 'PERMISSION_NOT_EXISTS',
  PERMISSION_CREATION_FAILED = 'PERMISSION_CREATION_FAILED',
  PERMISSION_IS_NOT_ACTIVE = 'PERMISSION_IS_NOT_ACTIVE',
  PERMISSION_Is_NOT_DESACTIVE = 'PERMISSION_Is_NOT_DESACTIVE',
  MAX_RESEND_ATTEMPTS_REACHED = 'MAX_RESEND_ATTEMPTS_REACHED',
  CIRCULAR_DEPENDENCY_DETECTED = 'CIRCULAR_DEPENDENCY_DETECTED',
  SYSTEM_PERMISSION_MODIFICATION_NOT_ALLOWED = 'SYSTEM_PERMISSION_MODIFICATION_NOT_ALLOWED',

  // Errores de autenticación
  PERMISSION_NOT_FOUND = 'PERMISSION_NOT_FOUND',
  PERMISSION_UNAUTHORIZED = 'PERMISSION_UNAUTHORIZED',
  // Errores de actualización de perfil
  PERMISSION_UPDATE_FAILED = 'PERMISSION_UPDATE_FAILED',
  // Errores de permisos y PERMISSIONes
  PERMISSION_INSUFFICIENT_PERMISSIONS = 'PERMISSION_INSUFFICIENT_PERMISSIONS',
  PERMISSION_ASSIGNMENT_FAILED = 'PERMISSION_ASSIGNMENT_FAILED',
  PERMISSION_REMOVAL_FAILED = 'PERMISSION_REMOVAL_FAILED',
  PERMISSION_NOT_VALID = 'PERMISSION_NOT_VALID',


  // Errores de eliminación de cuenta o datos
  PERMISSION_DELETION_FAILED = 'PERMISSION_DELETION_FAILED',

  PERMISSION_ALREADY_DELETED = 'PERMISSION_ALREADY_DELETED',
  PERMISSION_ALREADY_ACTIVE = 'PERMISSION_ALREADY_ACTIVE',
  SYSTEM_PERMISSION_DELETION_NOT_ALLOWED = 'SYSTEM_PERMISSION_DELETION_NOT_ALLOWED',
  PERMISSION_HAS_ACTIVE_DEPENDENCIES = 'PERMISSION_HAS_ACTIVE_DEPENDENCIES',
  PERMISSION_HAS_ACTIVE_ASSIGNMENTS = 'PERMISSION_HAS_ACTIVE_ASSIGNMENTS',
}

export enum LogisticsErrorCode {
  // Vehículos
  VEHICLE_NOT_FOUND            = 'VEHICLE_NOT_FOUND',
  VEHICLE_ALREADY_IN_COMPLEX   = 'VEHICLE_ALREADY_IN_COMPLEX',
  VEHICLE_PLATE_DUPLICATE      = 'VEHICLE_PLATE_DUPLICATE',
  VEHICLE_NOT_ACTIVE           = 'VEHICLE_NOT_ACTIVE',
  VEHICLE_SUSPENDED            = 'VEHICLE_SUSPENDED',
  VEHICLE_ALREADY_REMOVED      = 'VEHICLE_ALREADY_REMOVED',
  MAX_VEHICLES_PER_UNIT        = 'MAX_VEHICLES_PER_UNIT',
  PARKING_SPOT_NOT_AVAILABLE   = 'PARKING_SPOT_NOT_AVAILABLE',
  INVALID_PLATE_FORMAT         = 'INVALID_PLATE_FORMAT',
  // Paquetes
  PARCEL_NOT_FOUND             = 'PARCEL_NOT_FOUND',
  PARCEL_ALREADY_DELIVERED     = 'PARCEL_ALREADY_DELIVERED',
  PARCEL_STORAGE_FULL          = 'PARCEL_STORAGE_FULL',
  // Rotación de parqueaderos
  ROTATION_CONFIG_NOT_FOUND    = 'ROTATION_CONFIG_NOT_FOUND',
  ROTATION_INACTIVE            = 'ROTATION_INACTIVE',
  ROTATION_NOT_NEEDED          = 'ROTATION_NOT_NEEDED',
}


export enum AccessErrorCode {
  VISIT_NOT_AUTHORIZED          = 'VISIT_NOT_AUTHORIZED',
  VISIT_EXPIRED                 = 'VISIT_EXPIRED',
  VISIT_NOT_FOUND               = 'VISIT_NOT_FOUND',
  VISIT_ALREADY_INSIDE          = 'VISIT_ALREADY_INSIDE',
  VISIT_ALREADY_COMPLETED       = 'VISIT_ALREADY_COMPLETED',
  VISIT_ALREADY_DENIED          = 'VISIT_ALREADY_DENIED',
  VISITOR_BLACK_LISTED          = 'VISITOR_BLACK_LISTED',
  VISITOR_NOT_FOUND             = 'VISITOR_NOT_FOUND',
  VISITOR_ALREADY_BLACKLISTED   = 'VISITOR_ALREADY_BLACKLISTED',
  VISITOR_NOT_BLACKLISTED       = 'VISITOR_NOT_BLACKLISTED',
  QR_CODE_INVALID               = 'QR_CODE_INVALID',
  QR_CODE_ALREADY_USED          = 'QR_CODE_ALREADY_USED',
  QR_CODE_EXPIRED               = 'QR_CODE_EXPIRED',
  ENTRY_DENIED_BY_RESIDENT      = 'ENTRY_DENIED_BY_RESIDENT',
  GUARD_NOT_ASSIGNED_TO_COMPLEX = 'GUARD_NOT_ASSIGNED_TO_COMPLEX',
  DEVICE_OFFLINE                = 'DEVICE_OFFLINE',
}

export enum ResidentErrorCode {
  RESIDENT_NOT_FOUND              = 'RESIDENT_NOT_FOUND',
  RESIDENT_ALREADY_ACTIVE         = 'RESIDENT_ALREADY_ACTIVE',
  RESIDENT_ALREADY_PENDING        = 'RESIDENT_ALREADY_PENDING',
  RESIDENT_ALREADY_MAIN           = 'RESIDENT_ALREADY_MAIN',
  RESIDENT_SUSPENDED              = 'RESIDENT_SUSPENDED',
  RESIDENT_MOVED_OUT              = 'RESIDENT_MOVED_OUT',
  RESIDENT_REJECTED               = 'RESIDENT_REJECTED',
  USER_ALREADY_RESIDENT_IN_COMPLEX = 'USER_ALREADY_RESIDENT_IN_COMPLEX',
  CANNOT_REMOVE_ACTIVE_RESIDENT   = 'CANNOT_REMOVE_ACTIVE_RESIDENT',
}

export enum FinanceErrorCode {
  FEE_CONFIG_NOT_FOUND         = 'FEE_CONFIG_NOT_FOUND',
  FEE_CONFIG_ALREADY_EXISTS    = 'FEE_CONFIG_ALREADY_EXISTS',
  FEE_CONFIG_INACTIVE          = 'FEE_CONFIG_INACTIVE',
  FEE_CHARGE_NOT_FOUND         = 'FEE_CHARGE_NOT_FOUND',
  FEE_CHARGE_ALREADY_PAID      = 'FEE_CHARGE_ALREADY_PAID',
  FEE_CHARGE_CANCELLED         = 'FEE_CHARGE_CANCELLED',
  FEE_CHARGE_ALREADY_EXISTS    = 'FEE_CHARGE_ALREADY_EXISTS',
  PAYMENT_NOT_FOUND            = 'PAYMENT_NOT_FOUND',
  PAYMENT_EXCEEDS_BALANCE      = 'PAYMENT_EXCEEDS_BALANCE',
  PAYMENT_ALREADY_REVERSED     = 'PAYMENT_ALREADY_REVERSED',
  PERIOD_INVALID_FORMAT        = 'PERIOD_INVALID_FORMAT',
  PERIOD_ALREADY_CLOSED        = 'PERIOD_ALREADY_CLOSED',
  EXPENSE_NOT_FOUND            = 'EXPENSE_NOT_FOUND',
  EXPENSE_ALREADY_REVERSED     = 'EXPENSE_ALREADY_REVERSED',
}

export enum NoteErrorCode {
  NOTE_NOT_FOUND             = 'NOTE_NOT_FOUND',
  NOTE_ACCESS_DENIED         = 'NOTE_ACCESS_DENIED',
  NOTE_ALREADY_DELETED       = 'NOTE_ALREADY_DELETED',
  NOTE_COMPLEX_MISMATCH      = 'NOTE_COMPLEX_MISMATCH',
}

export enum MessageErrorCode {
  MESSAGE_NOT_FOUND    = 'MESSAGE_NOT_FOUND',
  MESSAGE_ACCESS_DENIED = 'MESSAGE_ACCESS_DENIED',
}

export enum AccessRequestErrorCode {
  ALREADY_ASSIGNED           = 'ALREADY_ASSIGNED',
  REQUEST_ALREADY_PENDING    = 'REQUEST_ALREADY_PENDING',
  REQUEST_NOT_FOUND          = 'REQUEST_NOT_FOUND',
  REQUEST_ALREADY_RESOLVED   = 'REQUEST_ALREADY_RESOLVED',
}

export enum SupervisorErrorCode {
  COMPLEX_NOT_FOUND_FOR_CHECKIN        = 'COMPLEX_NOT_FOUND_FOR_CHECKIN',
  SUPERVISOR_NOT_ASSIGNED_TO_COMPLEX   = 'SUPERVISOR_NOT_ASSIGNED_TO_COMPLEX',
  SUPERVISOR_VISIT_ALREADY_ACTIVE      = 'SUPERVISOR_VISIT_ALREADY_ACTIVE',
  SUPERVISOR_VISIT_NOT_FOUND           = 'SUPERVISOR_VISIT_NOT_FOUND',
  SUPERVISOR_VISIT_REQUIRED_FOR_NOTE   = 'SUPERVISOR_VISIT_REQUIRED_FOR_NOTE',
  SUPERVISOR_OUT_OF_RANGE              = 'SUPERVISOR_OUT_OF_RANGE',
  GPS_COORDINATES_REQUIRED             = 'GPS_COORDINATES_REQUIRED',
}

export enum ParkingErrorCode {
  PARKING_RECORD_NOT_FOUND           = 'PARKING_RECORD_NOT_FOUND',
  PARKING_VEHICLE_NOT_INSIDE         = 'PARKING_VEHICLE_NOT_INSIDE',
  PARKING_VEHICLE_ALREADY_EXITED     = 'PARKING_VEHICLE_ALREADY_EXITED',
  PARKING_RATE_NOT_FOUND             = 'PARKING_RATE_NOT_FOUND',
  PARKING_RATE_INACTIVE              = 'PARKING_RATE_INACTIVE',
  VISITOR_PARKING_CONFIG_NOT_FOUND   = 'VISITOR_PARKING_CONFIG_NOT_FOUND',
}

export enum SpecialNumberErrorCode {
  SPECIAL_NUMBER_NOT_FOUND        = 'SPECIAL_NUMBER_NOT_FOUND',
  SPECIAL_NUMBER_ACCESS_DENIED    = 'SPECIAL_NUMBER_ACCESS_DENIED',
  SPECIAL_NUMBER_COMPLEX_MISMATCH = 'SPECIAL_NUMBER_COMPLEX_MISMATCH',
  SPECIAL_NUMBER_COMPLEX_REQUIRED = 'SPECIAL_NUMBER_COMPLEX_REQUIRED',
  MAX_NUMBERS_REACHED             = 'MAX_NUMBERS_REACHED',
}

export enum ComplexErrorCode {
  COMPLEX_NOT_FOUND            = 'COMPLEX_NOT_FOUND',
  COMPLEX_ALREADY_EXISTS       = 'COMPLEX_ALREADY_EXISTS',
  COMPLEX_SUBSCRIPTION_EXPIRED = 'COMPLEX_SUBSCRIPTION_EXPIRED',
  BUILDING_NOT_FOUND           = 'BUILDING_NOT_FOUND',
  BUILDING_ALREADY_EXISTS      = 'BUILDING_ALREADY_EXISTS',
  BUILDING_HAS_ACTIVE_UNITS    = 'BUILDING_HAS_ACTIVE_UNITS',
  UNIT_NOT_FOUND               = 'UNIT_NOT_FOUND',
  UNIT_ALREADY_EXISTS          = 'UNIT_ALREADY_EXISTS',
  UNIT_IS_OCCUPIED             = 'UNIT_IS_OCCUPIED',
  INVALID_UNIT_FORMAT          = 'INVALID_UNIT_FORMAT',
  MAX_RESIDENTS_REACHED        = 'MAX_RESIDENTS_REACHED',
  PLAN_LIMIT_EXCEEDED           = 'PLAN_LIMIT_EXCEEDED',
  GEOCODING_ADDRESS_NOT_FOUND   = 'GEOCODING_ADDRESS_NOT_FOUND',
  GEOCODING_SERVICE_UNAVAILABLE = 'GEOCODING_SERVICE_UNAVAILABLE',
}
