/**
 * Encabezados en español de las columnas del respaldo, por nombre de
 * propiedad. Un campo nuevo que no esté aquí sale con su nombre técnico: el
 * respaldo no se rompe, solo se lee peor. Los ids llevan "(id)" porque al lado
 * sale su nombre legible.
 */
export const HEADER_LABELS: Record<string, string> = {
  // ── Comunes ──────────────────────────────────────────────────────────────
  id: 'ID',
  name: 'Nombre',
  lastName: 'Apellido',
  email: 'Correo',
  phone: 'Teléfono',
  phoneNumber: 'Teléfono',
  identity: 'Documento',
  identityType: 'Tipo de documento',
  status: 'Estado',
  type: 'Tipo',
  kind: 'Tipo',
  category: 'Categoría',
  title: 'Título',
  description: 'Descripción',
  notes: 'Notas',
  message: 'Mensaje',
  body: 'Mensaje',
  content: 'Contenido',
  text: 'Texto',
  comment: 'Comentario',
  code: 'Código',
  number: 'Número',
  reference: 'Referencia',
  referenceNumber: 'Número de referencia',
  consecutive: 'Consecutivo',
  version: 'Versión',
  position: 'Posición',
  reason: 'Motivo',
  rules: 'Reglas',
  purpose: 'Propósito',
  metadata: 'Datos adicionales',
  location: 'Ubicación',
  priority: 'Prioridad',
  severity: 'Gravedad',
  visibility: 'Visibilidad',
  channel: 'Canal',
  direction: 'Dirección',
  role: 'Rol',
  isActive: 'Activo',
  createdAt: 'Creado',
  updatedAt: 'Actualizado',
  deletedAt: 'Eliminado',
  createdByUserId: 'Creado por (id)',
  createdByRole: 'Rol de quien lo creó',
  updatedByUserId: 'Actualizado por (id)',
  complexId: 'Complejo (id)',
  unitId: 'Unidad (id)',
  buildingId: 'Torre (id)',
  userId: 'Usuario (id)',
  residentId: 'Residente (id)',

  // ── Fechas y plazos ──────────────────────────────────────────────────────
  startAt: 'Inicia',
  endAt: 'Termina',
  startsAt: 'Inicia',
  endsAt: 'Termina',
  startDate: 'Fecha de inicio',
  endDate: 'Fecha de fin',
  startedAt: 'Iniciado',
  endedAt: 'Terminado',
  scheduledAt: 'Programado',
  scheduledFor: 'Programado para',
  openedAt: 'Abierto',
  closedAt: 'Cerrado',
  resolvedAt: 'Resuelto',
  approvedAt: 'Aprobado',
  assignedAt: 'Asignado',
  removedAt: 'Retirado',
  expiresAt: 'Vence',
  dueDate: 'Vence',
  dueAt: 'Vence',
  paidAt: 'Pagado',
  sentAt: 'Enviado',
  readAt: 'Leído',
  receivedAt: 'Recibido',
  notifiedAt: 'Notificado',
  deliveredAt: 'Entregado',
  returnedAt: 'Devuelto',
  cancelledAt: 'Cancelado',
  confirmedAt: 'Confirmado',
  publishedAt: 'Publicado',
  renewedAt: 'Renovado',
  soldAt: 'Vendido',
  moderatedAt: 'Moderado',
  reviewedAt: 'Revisado',
  triagedAt: 'Revisado por la administración',
  answeredAt: 'Contestado',
  acknowledgedAt: 'Atendido',
  acceptedTermsAt: 'Aceptó términos',
  occurredAt: 'Ocurrió',
  ratedAt: 'Calificado',
  revertedAt: 'Revertido',
  reversedAt: 'Reversado',
  lastMovementAt: 'Último movimiento',
  lastReminderAt: 'Último recordatorio',
  lastReopenedAt: 'Última reapertura',
  reminderSentAt: 'Recordatorio enviado',
  expiryNotifiedAt: 'Aviso de vencimiento',
  statementDueAt: 'Plazo de descargos',
  slaDueAt: 'Plazo de atención',
  slaBreachedAt: 'Plazo incumplido',
  slaHours: 'Plazo (horas)',
  actionTakenAt: 'Acción tomada',
  approvedByResidentAt: 'Aprobado por el residente',
  deniedByResidentAt: 'Negado por el residente',
  damageChargedAt: 'Daño cobrado',
  rotationSuspendedAt: 'Rotación suspendida',
  blacklistedAt: 'Bloqueado',
  expectedArrivalAt: 'Llegada esperada desde',
  expectedArrivalUntil: 'Llegada esperada hasta',
  qrExpiresAt: 'QR vence',
  entryDate: 'Fecha de entrada',
  entryTime: 'Hora de entrada',
  exitDate: 'Fecha de salida',
  exitTime: 'Hora de salida',
  checkInAt: 'Entrada',
  checkOutAt: 'Salida',
  moveOutDate: 'Fecha de salida',
  birthDate: 'Fecha de nacimiento',
  documentDate: 'Fecha del documento',
  expenseDate: 'Fecha del gasto',
  incomeDate: 'Fecha del ingreso',
  earlyPaymentDueDate: 'Vence pronto pago',
  rabiesVaccineAt: 'Vacuna antirrábica',
  insuranceExpiresAt: 'Vence póliza',
  year: 'Año',
  duration: 'Duración',
  durationUnit: 'Unidad de duración',
  durationSeconds: 'Duración (segundos)',

  // ── Personas ─────────────────────────────────────────────────────────────
  authorName: 'Autor',
  authorRole: 'Rol del autor',
  authorUserId: 'Autor (id)',
  agentName: 'Agente',
  agentUserId: 'Agente (id)',
  contactName: 'Contacto',
  contactPreference: 'Preferencia de contacto',
  recipientName: 'Destinatario',
  recipientPhones: 'Teléfonos destinatarios',
  recipientUserId: 'Destinatario (id)',
  recipientCount: 'Destinatarios',
  residentName: 'Residente',
  reportedByName: 'Reportado por',
  reportedByRole: 'Rol de quien reportó',
  reportedByUserId: 'Reportado por (id)',
  reportedByUnitId: 'Unidad que reportó (id)',
  reporterUserId: 'Denunciante (id)',
  reporterUnitId: 'Unidad denunciante (id)',
  requestedByName: 'Solicitado por',
  requestedByUserId: 'Solicitado por (id)',
  performedById: 'Realizado por (id)',
  performedByName: 'Realizado por',
  performedByRole: 'Rol de quien lo hizo',
  ownerUserId: 'Propietario (id)',
  hostResidentId: 'Residente anfitrión (id)',
  supervisorId: 'Supervisor (id)',
  assignedUserId: 'Asignado a (id)',
  assignedByUserId: 'Asignado por (id)',
  approvedByUserId: 'Aprobado por (id)',
  registeredByUserId: 'Registrado por (id)',
  deliveredByUserId: 'Entregado por (id)',
  cancelledByUserId: 'Cancelado por (id)',
  checkedInByUserId: 'Ingreso registrado por (id)',
  checkedOutByUserId: 'Salida registrada por (id)',
  exitRegisteredByUserId: 'Salida registrada por (id)',
  closedByUserId: 'Cerrado por (id)',
  resolvedById: 'Resuelto por (id)',
  resolvedByUserId: 'Resuelto por (id)',
  reviewedByUserId: 'Revisado por (id)',
  triagedByUserId: 'Revisado por (id)',
  moderatedByUserId: 'Moderado por (id)',
  sentByUserId: 'Enviado por (id)',
  blacklistedByUserId: 'Bloqueado por (id)',
  damageChargedByUserId: 'Daño cobrado por (id)',
  reversedByUserId: 'Reversado por (id)',
  revertedById: 'Revertido por (id)',
  acknowledgedByUserId: 'Atendido por (id)',
  actionTakenByUserId: 'Acción tomada por (id)',
  triggeredByUserId: 'Activado por (id)',
  triggeredByLabel: 'Activado por',
  receivedByName: 'Recibido por',
  receivedByIdentity: 'Documento de quien recibió',
  senderName: 'Remitente',
  driverName: 'Conductor',
  thirdPartyName: 'Tercero',
  attendees: 'Asistentes',
  emergencyContactName: 'Contacto de emergencia',
  emergencyContactLastName: 'Apellido contacto de emergencia',
  emergencyContactPhone: 'Teléfono de emergencia',
  isMainResident: 'Residente principal',
  moveOutReason: 'Motivo de salida',

  // ── Unidades y torres ────────────────────────────────────────────────────
  floor: 'Piso',
  floors: 'Pisos',
  area: 'Área (m²)',
  bedrooms: 'Habitaciones',
  bathrooms: 'Baños',
  parkingSpots: 'Parqueaderos',
  parkingSpot: 'Parqueadero',
  storageRooms: 'Depósitos',
  hasElevator: 'Tiene ascensor',
  houseFloors: 'Pisos de la casa',
  coefficient: 'Coeficiente',
  unitNumber: 'Número de unidad',
  unitType: 'Tipo de unidad',
  buildingName: 'Torre',
  base: 'Base',
  elevatorPoints: 'Puntos por ascensor',
  houseFloorPoints: 'Puntos por piso de casa',
  perBathroom: 'Por baño',
  perBedroom: 'Por habitación',
  perParking: 'Por parqueadero',
  perStorage: 'Por depósito',
  typeMultipliers: 'Multiplicadores por tipo',

  // ── Visitas y vehículos ──────────────────────────────────────────────────
  visitorId: 'Visitante (id)',
  plate: 'Placa',
  vehiclePlate: 'Placa',
  vehicleType: 'Tipo de vehículo',
  vehicleTypes: 'Tipos de vehículo',
  brand: 'Marca',
  model: 'Modelo',
  color: 'Color',
  fuelType: 'Combustible',
  accessCode: 'Código de acceso',
  qrUsed: 'QR usado',
  isBlacklisted: 'En lista negra',
  blacklistReason: 'Motivo del bloqueo',
  denialReason: 'Motivo de la negación',
  rejectionReason: 'Motivo del rechazo',
  parkingCost: 'Costo de parqueadero',
  rotationCycleCount: 'Ciclos de rotación',
  suspendedByRotation: 'Suspendido por rotación',

  // ── Paquetes ─────────────────────────────────────────────────────────────
  trackingCode: 'Guía',
  maxStorageDays: 'Días máximos en portería',
  returnReason: 'Motivo de devolución',

  // ── Finanzas ─────────────────────────────────────────────────────────────
  amount: 'Valor',
  total: 'Total',
  balance: 'Saldo',
  currentBalance: 'Saldo actual',
  prepaidBalance: 'Saldo a favor',
  paidAmount: 'Valor pagado',
  normalAmount: 'Valor normal',
  earlyPaymentAmount: 'Valor con pronto pago',
  feeAmount: 'Valor de la cuota',
  fineAmount: 'Valor de la multa',
  damageAmount: 'Valor del daño',
  priceAmount: 'Precio',
  priceType: 'Tipo de precio',
  actualCost: 'Costo real',
  lateCancellationAmount: 'Cobro por cancelación tardía',
  lateCancellationFeePercent: 'Porcentaje por cancelación tardía',
  debit: 'Débito',
  credit: 'Crédito',
  totalDebit: 'Total débito',
  totalCredit: 'Total crédito',
  period: 'Periodo',
  concept: 'Concepto',
  conceptName: 'Concepto',
  prelacionConcept: 'Concepto de prelación',
  chargeType: 'Tipo de cargo',
  feeType: 'Tipo de cuota',
  chargeId: 'Cargo (id)',
  feeChargeId: 'Cargo (id)',
  feeConfigId: 'Configuración de cuota (id)',
  sourceChargeId: 'Cargo de origen (id)',
  fineChargeId: 'Cargo de la multa (id)',
  damageChargeId: 'Cargo del daño (id)',
  lateCancellationChargeId: 'Cargo por cancelación (id)',

  // Aseo de la zona común
  cleaningServiceAvailable: 'Ofrece servicio de aseo',
  defaultCleaningMinutes: 'Franja de aseo sugerida (min)',
  councilQuotaCoversCleaning: 'El cupo del consejo cubre el aseo',
  cleaningMinutes: 'Franja de aseo (min)',
  blockedUntilAt: 'Zona ocupada hasta',
  cleaningByComplex: 'Asea la administración',
  cleaningFeeAmount: 'Valor del aseo',
  cleaningChargeId: 'Cargo del aseo (id)',
  cleaningUpdatedAt: 'Aseo ajustado el',
  cleaningUpdatedByUserId: 'Aseo ajustado por (id)',

  // Pago del alquiler y devolución
  directIncomeId: 'Ingreso directo (id)',
  directPaymentAmount: 'Pagado en administración',
  directPaymentAt: 'Pagado en administración el',
  directPaymentByUserId: 'Pago recibido por (id)',
  refundAmount: 'Valor a devolver',
  refundVoucherId: 'Comprobante de devolución (id)',
  refundedAt: 'Devolución entregada el',
  categoryId: 'Categoría (id)',
  defaultCategory: 'Categoría por defecto',
  headerId: 'Comprobante (id)',
  reversesHeaderId: 'Reversa el comprobante (id)',
  reversedByHeaderId: 'Reversado por el comprobante (id)',
  pucAccountId: 'Cuenta PUC (id)',
  incomeAccountId: 'Cuenta de ingreso (id)',
  documentType: 'Tipo de documento contable',
  invoiceNumber: 'Número de factura',
  receiptUrl: 'Soporte',
  memo: 'Detalle',
  method: 'Medio',
  paymentMethod: 'Medio de pago',
  currency: 'Moneda',
  rate: 'Tarifa',
  frequency: 'Frecuencia',
  billingDay: 'Día de facturación',
  billingMode: 'Modo de facturación',
  lastBilledPeriod: 'Último periodo facturado',
  dueDayOfMonth: 'Día de vencimiento',
  earlyPaymentDueDayOfMonth: 'Día límite pronto pago',
  earlyDiscountDay: 'Día de descuento',
  earlyDiscountPct: 'Descuento (%)',
  installments: 'Cuotas',
  installmentsPaid: 'Cuotas pagadas',
  totalInstallments: 'Total de cuotas',
  currentInstallment: 'Cuota actual',
  prorateByCoefficient: 'Prorratear por coeficiente',
  distribution: 'Distribución',
  generatedCount: 'Cargos generados',
  isReversed: 'Reversado',
  reversalReason: 'Motivo de la reversión',
  blockBookingsOnDebt: 'Bloquear reservas con deuda',

  // ── Zonas comunes ────────────────────────────────────────────────────────
  amenityId: 'Zona común (id)',
  capacity: 'Capacidad',
  bookingMode: 'Modo de reserva',
  requiresApproval: 'Requiere aprobación',
  advanceBookingDays: 'Días de anticipación máximos',
  minAdvanceDays: 'Días de anticipación mínimos',
  maxDurationMinutes: 'Duración máxima (min)',
  minDurationMinutes: 'Duración mínima (min)',
  slotDurationMinutes: 'Franja (min)',
  maxActiveBookingsPerUnit: 'Reservas activas por unidad',
  maxBookingsPerUnitPerMonth: 'Reservas por unidad al mes',
  maxSimultaneousBookings: 'Reservas simultáneas',
  cancellationDeadlineDays: 'Días límite para cancelar',
  cancellationDeadlineHours: 'Horas límite para cancelar',
  cancellationReason: 'Motivo de cancelación',
  councilFreeBookingsPerYear: 'Reservas gratis del consejo al año',
  isCouncilFreeBooking: 'Reserva gratis del consejo',
  damageDescription: 'Descripción del daño',

  // ── PQRF ─────────────────────────────────────────────────────────────────
  subject: 'Asunto',
  addressee: 'Dirigido a',
  resolutionNote: 'Respuesta',
  resolutionNotes: 'Resolución',
  resolvedBySilence: 'Resuelto por silencio administrativo',

  // ── Votaciones ───────────────────────────────────────────────────────────
  meetingId: 'Asamblea (id)',
  questionId: 'Pregunta (id)',
  weighting: 'Ponderación',
  secrecy: 'Tipo de voto',
  eligibleCount: 'Votantes habilitados',
  eligibleWeight: 'Peso habilitado',
  isOptional: 'Opcional',

  // ── Mascotas ─────────────────────────────────────────────────────────────
  petId: 'Mascota (id)',
  incidentId: 'Reporte (id)',
  species: 'Especie',
  breed: 'Raza',
  sex: 'Sexo',
  size: 'Tamaño',
  sterilized: 'Esterilizada',
  hasMicrochip: 'Tiene microchip',
  microchipCode: 'Microchip',
  isSpecialBreed: 'Raza de manejo especial',
  insuranceCompany: 'Aseguradora',
  insurancePolicyNumber: 'Número de póliza',
  vaccinationCardUrl: 'Carné de vacunación',
  distinguishingMarks: 'Señas particulares',
  outcome: 'Decisión',

  // ── Mantenimiento ────────────────────────────────────────────────────────
  ticketId: 'Ticket (id)',
  vendorId: 'Proveedor (id)',
  locationTagId: 'Punto QR (id)',
  locationType: 'Tipo de ubicación',
  locationText: 'Ubicación descrita',
  assigneeType: 'Tipo de responsable',
  duplicateOfTicketId: 'Duplicado de (id)',
  endorsementCount: 'Adhesiones',
  reopenCount: 'Reaperturas',
  onHoldReason: 'Motivo de la pausa',
  rating: 'Calificación',
  ratingComment: 'Comentario de la calificación',
  fromStatus: 'Estado anterior',
  toStatus: 'Estado nuevo',
  isInternal: 'Interno',
  legalId: 'NIT / documento',
  specialties: 'Especialidades',
  closurePhotoUrls: 'Fotos del cierre',
  closurePhotoHashes: 'Huellas de las fotos del cierre',

  // ── Clasificados ─────────────────────────────────────────────────────────
  listingId: 'Aviso (id)',
  condition: 'Estado del artículo',
  showPhone: 'Muestra el teléfono',
  viewsCount: 'Vistas',
  favoritesCount: 'Favoritos',
  contactsCount: 'Contactos',
  pendingReportsCount: 'Denuncias pendientes',

  // ── Notificaciones, mensajes, auditoría ──────────────────────────────────
  isRead: 'Leída',
  isStarred: 'Destacada',
  isBroadcast: 'Masiva',
  isActionable: 'Requiere acción',
  actionType: 'Tipo de acción',
  actionLabel: 'Acción',
  actionResult: 'Resultado de la acción',
  messageType: 'Tipo de mensaje',
  targetRoles: 'Roles destinatarios',
  targetRules: 'Reglas de destinatarios',
  targetUnitIds: 'Unidades destinatarias (id)',
  panicAlertId: 'Alerta de pánico (id)',
  escalationLevel: 'Nivel de escalamiento',
  triggerType: 'Origen',
  entityType: 'Tipo de registro',
  entityId: 'Registro (id)',
  action: 'Acción',
  previousValue: 'Valor anterior',
  newValue: 'Valor nuevo',
  isReverted: 'Revertido',

  // ── Ubicación y evidencias ───────────────────────────────────────────────
  lat: 'Latitud',
  lng: 'Longitud',
  latitude: 'Latitud',
  longitude: 'Longitud',
  accuracy: 'Precisión GPS (m)',
  gpsAccuracyMeters: 'Precisión GPS (m)',
  checkInLat: 'Latitud de entrada',
  checkInLng: 'Longitud de entrada',
  requestLat: 'Latitud de la solicitud',
  requestLng: 'Longitud de la solicitud',
  photoUrl: 'Foto',
  photoUrls: 'Fotos',
  imageUrls: 'Imágenes',
  photoHashes: 'Huellas de las fotos',
  imageHashes: 'Huellas de las imágenes',
  videoUrl: 'Video',
  videoHash: 'Huella del video',
  supervisorVisitId: 'Visita de supervisor (id)',
};
